spring:
  resources:
    cache-period: 0
    static-locations: file:./client/

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
  file: 